# Generated by Django 5.2.7 on 2025-10-25 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("tech_stack", models.CharField(blank=True, max_length=200)),
                ("github_link", models.URLField(blank=True)),
                ("demo_link", models.URLField(blank=True)),
                ("image", models.ImageField(blank=True, upload_to="projects/")),
            ],
        ),
    ]
