# Generated by Django 5.2.7 on 2025-10-30 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_project_created_at_project_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="icon",
            field=models.ImageField(blank=True, null=True, upload_to="projects/icons/"),
        ),
    ]
