# Generated by Django 5.2.7 on 2025-10-31 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_project_icon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="tech_stack",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
