# Generated by Django 5.2.7 on 2025-10-31 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0004_alter_project_tech_stack"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="demo_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
