# Generated by Django 5.2.7 on 2025-11-27 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0005_project_demo_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="project_type",
            field=models.CharField(
                choices=[("static", "Static"), ("interactive", "Interactive")],
                default="static",
                max_length=20,
            ),
        ),
    ]
